name: Build and Deploy
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    environment:
      name: vue-press
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        if: success()
        with:
          target_branch: gh-pages
          build_dir: public
          jekyll: false
