name: Build and Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-upload-pages-artifact:
    runs-on: ubuntu-latest
    environment:
      name: vue-press
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .tool-versions
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependency and Build
        run: yarn && yarn docs:build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          name: github-pages
          path: docs/.vuepress/dist
